name = "Qilby Industries"
author = "Annwan, LunaFrejya"
version = "beta-5.2.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2b4c4f50c267e69777ad0b10bde4f2a03efb22be59016d8044abf6a49ad86e29"

[versions]
forge = "47.4.2"
minecraft = "1.20.1"
