name = "Qilby Industries"
author = "Annwan, LunaFrejya"
version = "beta-5.2.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0266c0ce8fe0df63fbfc78fb2a9c89a95c7c97ce74fd3cf05aa8521744982b96"

[versions]
forge = "47.4.2"
minecraft = "1.20.1"
