name = "Qilby Industries"
author = "Annwan, LunaFrejya"
version = "beta-4.5.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2261737edb4c51e36907d5f49fabc2783634ca690414afee97aa4371609794ea"

[versions]
forge = "47.4.2"
minecraft = "1.20.1"
