StartupEvents.registry('block', event => {
    event.create('dark_matter_coil', 'gtceu:coil').renderType("cutout_mipped")
        .temperature(12000)
        .level(18)
        .energyDiscount(16)
        .tier(8)
        .coilMaterial(() => GTMaterials.get('dark_energy'))
        .texture('gtceu:block/casings/coils/dark_matter')
        .hardness(5)
        .requiresTool(true)
        .soundType(SoundType.NETHERITE_BLOCK)
        .tagBlock('forge:mineable/wrench');

        event.create('dark_energy_coil', 'gtceu:coil').renderType("cutout_mipped")
        .temperature(26000)
        .level(20)
        .energyDiscount(16)
        .tier(9)
        .coilMaterial(() => GTMaterials.get('dark_energy'))
        .texture('gtceu:block/casings/coils/dark_matter')
        .hardness(5)
        .requiresTool(true)
        .soundType(SoundType.NETHERITE_BLOCK)
        .tagBlock('forge:mineable/wrench');

        event.create('runic_stellarite_coil', 'gtceu:coil').renderType("cutout_mipped")
        .temperature(50000)
        .level(22)
        .energyDiscount(16)
        .tier(9)
        .coilMaterial(() => GTMaterials.get('runic_stellarite'))
        .texture('gtceu:block/casings/coils/dark_matter')
        .hardness(5)
        .requiresTool(true)
        .soundType(SoundType.NETHERITE_BLOCK)
        .tagBlock('forge:mineable/wrench');

        event.create('stellarite_coil', 'gtceu:coil').renderType("cutout_mipped")
        .temperature(80000)
        .level(24)
        .energyDiscount(16)
        .tier(9)
        .coilMaterial(() => GTMaterials.get('stellarite'))
        .texture('gtceu:block/casings/coils/dark_matter')
        .hardness(5)
        .requiresTool(true)
        .soundType(SoundType.NETHERITE_BLOCK)
        .tagBlock('forge:mineable/wrench');

        event.create('fabric_of_reality_coil', 'gtceu:coil').renderType("cutout_mipped")
        .temperature(1000000)
        .level(26)
        .energyDiscount(16)
        .tier(9)
        .coilMaterial(() => GTMaterials.get('fabric_of_reality'))
        .texture('gtceu:block/casings/coils/dark_matter')
        .hardness(5)
        .requiresTool(true)
        .soundType(SoundType.NETHERITE_BLOCK)
        .tagBlock('forge:mineable/wrench');
});