ServerEvents.tags('item', event => {
//LV
event.add('gtceu:circuits/ulv','qilby_core:shushu_circuit_lv');
event.add('gtceu:circuits/lv','qilby_core:shushu_circuit_lv');
//MV
event.add('gtceu:circuits/ulv','qilby_core:shushu_circuit_mv');
event.add('gtceu:circuits/lv','qilby_core:shushu_circuit_mv');
event.add('gtceu:circuits/mv','qilby_core:shushu_circuit_mv');
//HV
event.add('gtceu:circuits/ulv','qilby_core:shushu_circuit_hv');
event.add('gtceu:circuits/lv','qilby_core:shushu_circuit_hv');
event.add('gtceu:circuits/mv','qilby_core:shushu_circuit_hv');
event.add('gtceu:circuits/hv','qilby_core:shushu_circuit_hv');
//EV
event.add('gtceu:circuits/ulv','qilby_core:shushu_circuit_ev');
event.add('gtceu:circuits/lv','qilby_core:shushu_circuit_ev');
event.add('gtceu:circuits/mv','qilby_core:shushu_circuit_ev');
event.add('gtceu:circuits/hv','qilby_core:shushu_circuit_ev');
event.add('gtceu:circuits/ev','qilby_core:shushu_circuit_ev');
//IV
event.add('gtceu:circuits/ulv','qilby_core:shushu_circuit_iv');
event.add('gtceu:circuits/lv','qilby_core:shushu_circuit_iv');
event.add('gtceu:circuits/mv','qilby_core:shushu_circuit_iv');
event.add('gtceu:circuits/hv','qilby_core:shushu_circuit_iv');
event.add('gtceu:circuits/ev','qilby_core:shushu_circuit_iv');
event.add('gtceu:circuits/iv','qilby_core:shushu_circuit_iv');
//LuV
event.add('gtceu:circuits/ulv','qilby_core:shushu_circuit_luv');
event.add('gtceu:circuits/lv','qilby_core:shushu_circuit_luv');
event.add('gtceu:circuits/mv','qilby_core:shushu_circuit_luv');
event.add('gtceu:circuits/hv','qilby_core:shushu_circuit_luv');
event.add('gtceu:circuits/ev','qilby_core:shushu_circuit_luv');
event.add('gtceu:circuits/iv','qilby_core:shushu_circuit_luv');
event.add('gtceu:circuits/luv','qilby_core:shushu_circuit_luv');
//ZPM
event.add('gtceu:circuits/ulv','qilby_core:shushu_circuit_zpm');
event.add('gtceu:circuits/lv','qilby_core:shushu_circuit_zpm');
event.add('gtceu:circuits/mv','qilby_core:shushu_circuit_zpm');
event.add('gtceu:circuits/hv','qilby_core:shushu_circuit_zpm');
event.add('gtceu:circuits/ev','qilby_core:shushu_circuit_zpm');
event.add('gtceu:circuits/iv','qilby_core:shushu_circuit_zpm');
event.add('gtceu:circuits/luv','qilby_core:shushu_circuit_zpm');
event.add('gtceu:circuits/zpm','qilby_core:shushu_circuit_zpm');
//UV
event.add('gtceu:circuits/ulv','qilby_core:shushu_circuit_uv');
event.add('gtceu:circuits/lv','qilby_core:shushu_circuit_uv');
event.add('gtceu:circuits/mv','qilby_core:shushu_circuit_uv');
event.add('gtceu:circuits/hv','qilby_core:shushu_circuit_uv');
event.add('gtceu:circuits/ev','qilby_core:shushu_circuit_uv');
event.add('gtceu:circuits/iv','qilby_core:shushu_circuit_uv');
event.add('gtceu:circuits/luv','qilby_core:shushu_circuit_uv');
event.add('gtceu:circuits/zpm','qilby_core:shushu_circuit_uv');
event.add('gtceu:circuits/uv','qilby_core:shushu_circuit_uv');
//UHV
event.add('gtceu:circuits/ulv','qilby_core:shushu_circuit_uhv');
event.add('gtceu:circuits/lv','qilby_core:shushu_circuit_uhv');
event.add('gtceu:circuits/mv','qilby_core:shushu_circuit_uhv');
event.add('gtceu:circuits/hv','qilby_core:shushu_circuit_uhv');
event.add('gtceu:circuits/ev','qilby_core:shushu_circuit_uhv');
event.add('gtceu:circuits/iv','qilby_core:shushu_circuit_uhv');
event.add('gtceu:circuits/luv','qilby_core:shushu_circuit_uhv');
event.add('gtceu:circuits/zpm','qilby_core:shushu_circuit_uhv');
event.add('gtceu:circuits/uv','qilby_core:shushu_circuit_uhv');
event.add('gtceu:circuits/uhv','qilby_core:shushu_circuit_uhv');
//UEV
event.add('gtceu:circuits/ulv','qilby_core:shushu_circuit_uev');
event.add('gtceu:circuits/lv','qilby_core:shushu_circuit_uev');
event.add('gtceu:circuits/mv','qilby_core:shushu_circuit_uev');
event.add('gtceu:circuits/hv','qilby_core:shushu_circuit_uev');
event.add('gtceu:circuits/ev','qilby_core:shushu_circuit_uev');
event.add('gtceu:circuits/iv','qilby_core:shushu_circuit_uev');
event.add('gtceu:circuits/luv','qilby_core:shushu_circuit_uev');
event.add('gtceu:circuits/zpm','qilby_core:shushu_circuit_uev');
event.add('gtceu:circuits/uv','qilby_core:shushu_circuit_uev');
event.add('gtceu:circuits/uhv','qilby_core:shushu_circuit_uev');
event.add('gtceu:circuits/uev','qilby_core:shushu_circuit_uev');
//UIV
event.add('gtceu:circuits/ulv','qilby_core:shushu_circuit_uiv');
event.add('gtceu:circuits/lv','qilby_core:shushu_circuit_uiv');
event.add('gtceu:circuits/mv','qilby_core:shushu_circuit_uiv');
event.add('gtceu:circuits/hv','qilby_core:shushu_circuit_uiv');
event.add('gtceu:circuits/ev','qilby_core:shushu_circuit_uiv');
event.add('gtceu:circuits/iv','qilby_core:shushu_circuit_uiv');
event.add('gtceu:circuits/luv','qilby_core:shushu_circuit_uiv');
event.add('gtceu:circuits/zpm','qilby_core:shushu_circuit_uiv');
event.add('gtceu:circuits/uv','qilby_core:shushu_circuit_uiv');
event.add('gtceu:circuits/uhv','qilby_core:shushu_circuit_uiv');
event.add('gtceu:circuits/uev','qilby_core:shushu_circuit_uiv');
event.add('gtceu:circuits/uiv','qilby_core:shushu_circuit_uiv');
//UXV
event.add('gtceu:circuits/ulv','qilby_core:shushu_circuit_uxv');
event.add('gtceu:circuits/lv','qilby_core:shushu_circuit_uxv');
event.add('gtceu:circuits/mv','qilby_core:shushu_circuit_uxv');
event.add('gtceu:circuits/hv','qilby_core:shushu_circuit_uxv');
event.add('gtceu:circuits/ev','qilby_core:shushu_circuit_uxv');
event.add('gtceu:circuits/iv','qilby_core:shushu_circuit_uxv');
event.add('gtceu:circuits/luv','qilby_core:shushu_circuit_uxv');
event.add('gtceu:circuits/zpm','qilby_core:shushu_circuit_uxv');
event.add('gtceu:circuits/uv','qilby_core:shushu_circuit_uxv');
event.add('gtceu:circuits/uhv','qilby_core:shushu_circuit_uxv');
event.add('gtceu:circuits/uev','qilby_core:shushu_circuit_uxv');
event.add('gtceu:circuits/uiv','qilby_core:shushu_circuit_uxv');
event.add('gtceu:circuits/uxv','qilby_core:shushu_circuit_uxv');
//OpV
event.add('gtceu:circuits/ulv','qilby_core:shushu_circuit_opv');
event.add('gtceu:circuits/lv','qilby_core:shushu_circuit_opv');
event.add('gtceu:circuits/mv','qilby_core:shushu_circuit_opv');
event.add('gtceu:circuits/hv','qilby_core:shushu_circuit_opv');
event.add('gtceu:circuits/ev','qilby_core:shushu_circuit_opv');
event.add('gtceu:circuits/iv','qilby_core:shushu_circuit_opv');
event.add('gtceu:circuits/luv','qilby_core:shushu_circuit_opv');
event.add('gtceu:circuits/zpm','qilby_core:shushu_circuit_opv');
event.add('gtceu:circuits/uv','qilby_core:shushu_circuit_opv');
event.add('gtceu:circuits/uhv','qilby_core:shushu_circuit_opv');
event.add('gtceu:circuits/uev','qilby_core:shushu_circuit_opv');
event.add('gtceu:circuits/uiv','qilby_core:shushu_circuit_opv');
event.add('gtceu:circuits/uxv','qilby_core:shushu_circuit_opv');
event.add('gtceu:circuits/opv','qilby_core:shushu_circuit_opv');
//MAX
event.add('gtceu:circuits/ulv','qilby_core:shushu_circuit_max');
event.add('gtceu:circuits/lv','qilby_core:shushu_circuit_max');
event.add('gtceu:circuits/mv','qilby_core:shushu_circuit_max');
event.add('gtceu:circuits/hv','qilby_core:shushu_circuit_max');
event.add('gtceu:circuits/ev','qilby_core:shushu_circuit_max');
event.add('gtceu:circuits/iv','qilby_core:shushu_circuit_max');
event.add('gtceu:circuits/luv','qilby_core:shushu_circuit_max');
event.add('gtceu:circuits/zpm','qilby_core:shushu_circuit_max');
event.add('gtceu:circuits/uv','qilby_core:shushu_circuit_max');
event.add('gtceu:circuits/uhv','qilby_core:shushu_circuit_max');
event.add('gtceu:circuits/uev','qilby_core:shushu_circuit_max');
event.add('gtceu:circuits/uiv','qilby_core:shushu_circuit_max');
event.add('gtceu:circuits/uxv','qilby_core:shushu_circuit_max');
event.add('gtceu:circuits/opv','qilby_core:shushu_circuit_max');
event.add('gtceu:circuits/max','qilby_core:shushu_circuit_max');
});